# Name of your workflow
name: NX release

# Rules that trigger the workflow
on:
  push:
    branches:
      - main
env:
  # NX release needs to have a GH token in env.GITHUB_TOKEN
  # As during this workflow we will create a new release
  # that should trigger other workflow, we need to create custom TOKEN
  # with proper permissions,
  # more: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 10
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Sets the base and head SHAs for the nx affected commands in CI
        uses: nrwl/nx-set-shas@v4

      - name: Build affected libs
        run: pnpx nx run-many -t build

      - name: Run nx release
        run: |
          git config --global user.email "briefe@kebes.de"
          git config --global user.name "torfmaster"
          pnpx nx release --skip-publish
          git push --follow-tags
      - name: Run nx release publish
        run: |
          pnpx nx release publish
